name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  flutter_secure_storage: ^5.0.2
  uuid: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
