name: store_service
description: Dart package which manages the store service.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  geolocator: ^9.0.1
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
